BuilkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BuilkyBook.DataAccess.Repository.IRepository;
using BuilkyBook.Model;
using BuilkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BuilkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CoverTypeController : Controller
    {

        private readonly IUnitWork _unitwork;

        public CoverTypeController(IUnitWork unitwork)
        {
            _unitwork = unitwork;
        }

        public IActionResult Index()
        {
            IEnumerable<CoverType> categoryList = _unitwork.CoverType.GetAll();
            return View(categoryList);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {


            if (ModelState.IsValid)
            {
                _unitwork.CoverType.Add(obj);
                _unitwork.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("index");
            }

            return View(obj);
        }


        public IActionResult Edit(int? id)
        {

            var categoryObj = _unitwork.CoverType.GetFirstOrDefault(u => u.id == id);
            if (categoryObj == null)
            {
                return NotFound();
            }
            return View(categoryObj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            if (obj.name == obj.id.ToString())
            {
                ModelState.AddModelError("name", "Name and Display order cannot be same");
            }
            if (ModelState.IsValid)
            {
                _unitwork.CoverType.Update(obj);
                _unitwork.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("index");
            }

            return View(obj);
        }



        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryObj = _unitwork.CoverType.GetFirstOrDefault(u => u.id == id);
            if (categoryObj == null)
            {
                return NotFound();
            }
            return View(categoryObj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(CoverType obj)
        {
            _unitwork.CoverType.Remove(obj);
            _unitwork.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("index");

        }
    }
}

BuilkyBookWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
    <div class="border mt-4 p-3">
        <div class="row pb-2">
            <h2 class="text-primary">Create Cover Type</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="name"></label>
            <input asp-for="name"  class="form-control"/>
            <span asp-validation-for="name" class="text-danger"></span>
        </div
       <div class="mt-3">
         <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="CoverType" asp-action="Index" style="width:150px" class="btn btn-secondary">Go Back</a>
      </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BuilkyBookWeb/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

<form method="post">
    <div class="border mt-4 p-3">
        <div class="row pb-2">
            <h2 class="text-primary">Delete a CoverType</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="name"></label>
            <input asp-for="name"  class="form-control" disabled/>
          
        </div
       <div class="mt-3">
         <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="CoverType" asp-action="Index" style="width:150px" class="btn btn-secondary">Go Back</a>
      </div>
    </div>
</form>

BuilkyBookWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post">
    <div class="border mt-4 p-3">
        <div class="row pb-2">
            <h2 class="text-primary">Edit a CoverType</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="name"></label>
            <input asp-for="name"  class="form-control"/>
            <span asp-validation-for="name" class="text-danger"></span>
        </div
       <div class="mt-3">
         <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="CoverType" asp-action="Index" style="width:150px" class="btn btn-secondary">Go Back</a>
      </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BuilkyBookWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}




<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Cover Type List</h2>
        </div>
        <div class="col-6">
           <a  asp-controller="CoverType" asp-action="Create" class="btn btn-primary p-2"><i class="bi bi-plus-circle"></i>&nbsp; Create New Cover Type</a>
        </div>
    </div>
    <br />
   
    <table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Cover Type Name</th>
             <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td width="50%">@item.name</td>
                  <td>
                      <div class="w-75 btn-group" role="group">
                          <a class="btn btn-primary actions me-4" asp-controller="CoverType" asp-action="Edit" asp-route-id="@item.id">
                              <i class="bi bi-pencil-square"></i>
                          </a>
                          <a class="btn btn-danger actions" asp-controller="CoverType" asp-action="Delete" asp-route-id="@item.id">
                             <i class="bi bi-trash3-fill"></i>
                          </a>
                      </div>
                     
         
                  </td>
            </tr>
        }
    </tbody>
</table>

</div>