BuilkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BuilkyBook.DataAccess.Data;
using BuilkyBook.DataAccess.Repository.IRepository;
using BuilkyBook.Model;
using BuilkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BuilkyBookWeb.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitWork _unitwork;

        public CategoryController(IUnitWork unitwork)
        {
            _unitwork = unitwork;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> categoryList = _unitwork.Category.GetAll();
            return View(categoryList);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.name == obj.displayOrder.ToString())
            {
                ModelState.AddModelError("name", "Name and Display order cannot be same");
            }
            if (ModelState.IsValid)
            {
                _unitwork.Category.Add(obj);
                _unitwork.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("index");
            }

            return View(obj);
        }


        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryObj = _unitwork.Category.GetFirstOrDefault(u => u.id == id);
            if (categoryObj == null)
            {
                return NotFound();
            }
            return View(categoryObj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.name == obj.displayOrder.ToString())
            {
                ModelState.AddModelError("name", "Name and Display order cannot be same");
            }
            if (ModelState.IsValid)
            {
                _unitwork.Category.Update(obj);
                _unitwork.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("index");
            }

            return View(obj);
        }



        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryObj = _unitwork.Category.GetFirstOrDefault(u => u.id == id);
            if (categoryObj == null)
            {
                return NotFound();
            }
            return View(categoryObj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Category obj)
        {
            _unitwork.Category.Remove(obj);
            _unitwork.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("index");

        }
    }
}

BuilkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using BuilkyBook.DataAccess.Repository.IRepository;
using BuilkyBook.Model;
using BuilkyBook.Model.ViewModel;
using BuilkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BuilkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitWork _unitwork;


        public CompanyController(IUnitWork unitwork)
        {
            _unitwork = unitwork;

        }

        public IActionResult Index()
        {

            return View();
        }


        public IActionResult Upsert(int? id)
        {
            Company company = new Company();

            if (id == 0 || id == null)
            {
                //ViewBag.CategoryList = CategoryList;
                //ViewBag.CoverTypeList = CoverTypeList;
                return View(company);
            }
            else
            {
                company = _unitwork.Company.GetFirstOrDefault(u => u.Id == id);
                return View(company);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company obj)
        {

            if (ModelState.IsValid)
            {

                if (obj.Id == 0)
                {
                    _unitwork.Company.Add(obj);
                    TempData["success"] = "Company created  successfully";
                }
                else
                {
                    _unitwork.Company.Update(obj);
                    TempData["success"] = "Company updated  successfully";
                }

                _unitwork.Save();
                return RedirectToAction("index");
            }

            return View(obj);
        }




        //API endpoint
        #region
        [HttpGet]
        public IActionResult GetAll()
        {
            var companyList = _unitwork.Company.GetAll();
            return Json(new { data = companyList });
        }
        #endregion

        #region
        [HttpDelete]
        public IActionResult Delete(int? id)
        {

            var Obj = _unitwork.Company.GetFirstOrDefault(u => u.Id == id);
            if (Obj == null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }

            _unitwork.Company.Remove(Obj);
            _unitwork.Save();
            return Json(new { success = true, message = "Delete Successfully" });
        }
        #endregion
    }
}

BuilkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using BuilkyBook.DataAccess.Repository.IRepository;
using BuilkyBook.Model;
using BuilkyBook.Model.ViewModel;
using BuilkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BuilkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitWork _unitwork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitWork unitwork, IWebHostEnvironment webHostEnvironment)
        {
            _unitwork = unitwork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {

            return View();
        }


        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                product = new(),
                CategoryList = _unitwork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.name,
                    Value = u.id.ToString(),
                }),
                CoverTypeList = _unitwork.CoverType.GetAll().Select(u => new SelectListItem
                {
                    Text = u.name,
                    Value = u.id.ToString(),
                }),

            };

            ////Pass data using viewbag and create drop down using selectItem
            //Product product = new Product();
            //IEnumerable<SelectListItem> CategoryList = _unitwork.Category.GetAll().Select(u => new SelectListItem
            //{
            //    Text = u.name,
            //    Value = id.ToString(),
            //});
            //IEnumerable<SelectListItem> CoverTypeList = _unitwork.CoverType.GetAll().Select(u => new SelectListItem
            //{
            //    Text = u.name,
            //    Value = id.ToString(),
            //});
            if (id == 0 || id == null)
            {
                //ViewBag.CategoryList = CategoryList;
                //ViewBag.CoverTypeList = CoverTypeList;
                return View(productVM);
            }
            else
            {
                productVM.product = _unitwork.Product.GetFirstOrDefault(u => u.Id == id);
                return View(productVM);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                string rootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(rootPath, @"Images/Products");
                    var extention = Path.GetExtension(file.FileName);

                    if (obj.product.ImageUrl != null)
                    {
                        var oldImgPath = Path.Combine(rootPath, obj.product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImgPath))
                        {
                            System.IO.File.Delete(oldImgPath);
                        }
                    }
                    //copy file
                    using (var fileStram = new FileStream(Path.Combine(uploads, fileName + extention), FileMode.Create))
                    {
                        file.CopyTo(fileStram);
                    };

                    obj.product.ImageUrl = @"Images/Products/" + fileName + extention;
                }

                if (obj.product.Id == 0)
                {
                    _unitwork.Product.Add(obj.product);
                }
                else
                {
                    _unitwork.Product.Update(obj.product);
                }

                _unitwork.Save();
                TempData["success"] = "Product created  successfully";
                return RedirectToAction("index");
            }

            return View(obj);
        }




        //API endpoint
        #region
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitwork.Product.GetAll(includeProperties: "Category,CoverType");
            return Json(new { data = productList });
        }
        #endregion

        #region
        [HttpDelete]
        public IActionResult Delete(int? id)
        {

            var Obj = _unitwork.Product.GetFirstOrDefault(u => u.Id == id);
            if (Obj == null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }
            var oldImgPath = Path.Combine(_webHostEnvironment.WebRootPath, Obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImgPath))
            {
                System.IO.File.Delete(oldImgPath);
            }
            _unitwork.Product.Remove(Obj);
            _unitwork.Save();
            return Json(new { success = true, message = "Delete Successfully" });
        }
        #endregion
    }
}

BuilkyBookWeb/ViewComponents/ShoppingCartViewComponent.cs
using BuilkyBook.DataAccess.Repository.IRepository;
using BuilkyBook.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BuilkyBookWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitWork _unitWork;
        public ShoppingCartViewComponent(IUnitWork unitWork)
        {
            _unitWork = unitWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitWork.ShopingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

BuilkyBookWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using BuilkyBook.Utility
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Builky Book </title>
   <link rel="stylesheet" href="~/css/BootsWatchThem.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css">
	<link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />

    
</head>
<body>
    <header>
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<div class="container-fluid">
				<a class="navbar-brand" href="#">Bulky Book</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarColor02">
					<ul class="navbar-nav me-auto">
						<li class="nav-item">

							<a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
						</li>	
						@if(User.IsInRole(SD.Role_Admin)){
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
								<div class="dropdown-menu">
									<a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
									<a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
									<div class="dropdown-divider"></div>
									  <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
									  <div class="dropdown-divider"></div>
									<a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
								</div>
							</li>
						}
							
							<li class="nav-item">

							<a class="nav-link " asp-area="Admin" asp-controller="Order" asp-action="Index">
								Manage Order
							</a>
						</li>
							<li class="nav-item">

							<a class="nav-link " asp-area="Customer" asp-controller="Cart" asp-action="Index">
								@await Component.InvokeAsync("ShoppingCart")
								
							</a>
							</li>
						
					</ul>
					<partial name="_LoginPartial" />
					
				</div>
			</div>
		</nav>

	</header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Builky Book
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script src="https://cdn.tiny.cloud/1/6qhq0231eaqy923m6qrcc9y7padwvj1xa2wy9ugpbgftzp6o/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BuilkyBookWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if(TempData["error"] != null)
{
     <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.errors('@TempData["error"]')
    </script>
    
}